import { CButton } from '@/components/button';
import { CEChart } from '@/components/echart';
import { CModalForm } from '@/components/form/modal';
import { EFormRuleType, EFormType, ETypeChart } from '@/enums';
import type { IEditTable, IForm } from '@/interfaces';
import type { IMCode, IMCodeType } from '@/interfaces/model';
import { SCrud } from '@/services';
import { formatDataChart } from '@/utils';

/**
 * Renders the dashboard page.
 *
 * @returns The rendered dashboard page.
 */
export const Component = () => {
  const sCrud = SCrud<IMCode, IMCodeType>('Code', 'CodeType');

  return (
    <div className='h-full pb-10'>
      <CButton onClick={() => sCrud.set({ isVisible: true })} text='Modal Form' />
      <CModalForm
        facade={sCrud}
        title={() => 'Modal Form'}
        columns={columns}
        onSubmit={({ value }) => console.log(value)}
      />
      {dataDefault.map((item, index) => (
        <CEChart key={index + 'chart'} option={item}></CEChart>
      ))}
      {/* <CGantt
        maxHeight={500}
        dateStart='2015-07-06'
        dateEnd='2015-09-04'
        data={task}
        event={event}
        perRow={1}
        columns={[
          { name: 'name', title: 'Product Release', tableItem: {} },
          { name: 'assignee', title: 'Assignee', tableItem: {} },
          {
            name: 'status',
            title: 'Status',
            tableItem: {
              width: 100,
            },
          },
          {
            name: 'priority',
            title: 'Priority',
            tableItem: {
              width: 80,
            },
          },
          {
            name: 'planned',
            title: 'Planned',
            tableItem: {
              width: 80,
              render: text => (text ? text + ' hours' : ''),
            },
          },
          {
            name: 'work',
            title: 'Work Log',
            tableItem: {
              width: 80,
              render: text => (text ? text + ' day' : ''),
            },
          },
        ]}
      />
      <div className='relative h-96 w-full'>
        <CFlow initialTree={initialTree} />
      </div> */}
    </div>
  );
};
const table: IEditTable = {
  fields: {
    columns: [
      { key: 'content' },
      { key: 'code' },
      {
        key: 'from',
        children: [{ key: 'from2', children: [{ key: 'totalFrom' }, { key: 'numberFrom' }] }],
      },
      {
        key: 'to',
        children: [{ key: 'to2', children: [{ key: 'totalTo' }, { key: 'numberTo' }] }],
      },
      { key: 'note' },
    ],
  },
  meta: [
    {
      field: 'content',
      name: 'Nội dung',
      fullName: 'Nội dung',
      type: 'title',
    },
    {
      field: 'code',
      name: 'Mã số',
      fullName: 'Mã số',
      type: 'title',
    },
    {
      field: 'from',
      name: 'Nơi tới',
      fullName: 'Nơi tới',
      type: 'title',
    },
    {
      field: 'from2',
      name: 'Nơi tới 2',
      fullName: 'Nơi tới 2',
      type: 'title',
    },
    {
      field: 'totalFrom',
      name: 'Tổng số hộ',
      fullName: 'Tổng số hộ tới',
      type: 'number',
    },
    {
      field: 'numberFrom',
      name: 'Số hộ DTTS',
      fullName: 'Số hộ DTTS tới',
      type: 'number',
    },
    {
      field: 'to',
      name: 'Nơi đi',
      fullName: 'Nơi đi',
      type: 'title',
    },
    {
      field: 'to2',
      name: 'Nơi đi 2',
      fullName: 'Nơi đi 2',
      type: 'title',
    },
    {
      field: 'totalTo',
      name: 'Tổng số hộ',
      fullName: 'Tổng số hộ đi',
      type: 'number',
    },
    {
      field: 'numberTo',
      name: 'Số hộ DTTS',
      fullName: 'Số hộ DTTS đi',
      type: 'number',
    },
    {
      field: 'note',
      name: 'Ghi chú',
      fullName: 'Ghi chú',
      type: 'text',
    },
  ],
  data: [
    {
      content: 'Tổng cả tỉnh',
      code: 'xx02',
      totalFrom: 27,
      numberFrom: 35,
      totalTo: 31,
      numberTo: 27,
      note: '',
      order: 1,
      level: 0,
      isSummary: true,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_SUMMARY.DISTRICT',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px; font-weight:bold;',
    },
    {
      content: 'Quận Ba Đình',
      code: 'yy',
      totalFrom: 8,
      numberFrom: 10,
      totalTo: 9,
      numberTo: 8,
      note: '',
      order: 2,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H001',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 8,
      numberFrom: 10,
      totalTo: 9,
      numberTo: 8,
      note: '',
      order: 3,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phúc Xá',
      code: 'T',
      totalFrom: 5,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 5,
      note: '',
      order: 4,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00001',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Trúc Bạch',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 5,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00004',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Vĩnh Phúc',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 6,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H001_X00006',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 8,
      numberFrom: 4,
      totalTo: 6,
      numberTo: 8,
      note: '',
      order: 7,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 8,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_DT01',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 9,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H001_DT02',
      maCha: 'B1-BIEU-1_T01_H001',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Hoàn Kiếm',
      code: 'yy',
      totalFrom: 9,
      numberFrom: 9,
      totalTo: 10,
      numberTo: 9,
      note: '',
      order: 10,
      level: 1,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H002',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 9,
      numberFrom: 9,
      totalTo: 10,
      numberTo: 9,
      note: '',
      order: 11,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phúc Tân',
      code: 'T',
      totalFrom: 4,
      numberFrom: 4,
      totalTo: 7,
      numberTo: 4,
      note: '',
      order: 12,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00037',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Đồng Xuân',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 13,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00040',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Hàng Ma',
      code: 'T',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 14,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H002_X00043',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 6,
      numberFrom: 6,
      totalTo: 8,
      numberTo: 6,
      note: '',
      order: 15,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 5,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 5,
      note: '',
      order: 16,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_DT01',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 17,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H002_DT02',
      maCha: 'B1-BIEU-1_T01_H002',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Tây Hồ',
      code: 'yy',
      totalFrom: 7,
      numberFrom: 9,
      totalTo: 8,
      numberTo: 7,
      note: '',
      order: 1,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H003',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 7,
      numberFrom: 9,
      totalTo: 8,
      numberTo: 7,
      note: '',
      order: 3,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Phú Thượng',
      code: 'T',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 4,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00091',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Nhật Tân',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 5,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00094',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Tứ Liên',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 6,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H003_X00097',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 7,
      numberFrom: 3,
      totalTo: 5,
      numberTo: 7,
      note: '',
      order: 7,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 8,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_DT01',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 9,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H003_DT02',
      maCha: 'B1-BIEU-1_T01_H003',
      style: 'font-size:14px;',
    },
    {
      content: 'Quận Long Biên',
      code: 'yy',
      totalFrom: 6,
      numberFrom: 8,
      totalTo: 7,
      numberTo: 6,
      note: '',
      order: 10,
      level: 1,
      isSummary: false,
      idBieuNoiDung: 'ab95cabc-2a58-43dc-b664-96c24e35fa97',
      ma: 'B1-BIEU-1_T01_H004',
      maCha: 'B1-BIEU-1_T01',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo phường xã',
      code: 'yy04',
      totalFrom: 6,
      numberFrom: 8,
      totalTo: 7,
      numberTo: 6,
      note: '',
      order: 11,
      level: 1,
      isSummary: true,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_SUMMARY.COMMUNE',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px; font-style:italic;',
    },
    {
      content: 'Phường Thượng Thanh',
      code: 'T',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 12,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00115',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Ngọc Thụy',
      code: 'T',
      totalFrom: 2,
      numberFrom: 4,
      totalTo: 1,
      numberTo: 2,
      note: '',
      order: 13,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00118',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Phường Giang Biên',
      code: 'T',
      totalFrom: 3,
      numberFrom: 1,
      totalTo: 2,
      numberTo: 3,
      note: '',
      order: 14,
      level: 2,
      isSummary: false,
      idBieuNoiDung: '19124fdd-7cc4-4ca8-9b99-6ece9f5e8209',
      ma: 'B1-BIEU-1_T01_H004_X00121',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Tổng số phân theo dân tộc',
      code: 'yy05',
      totalFrom: 5,
      numberFrom: 5,
      totalTo: 7,
      numberTo: 5,
      note: '',
      order: 15,
      level: 1,
      isSummary: true,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_SUMMARY.ETHNIC',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-style:italic;',
    },
    {
      content: 'Kinh',
      code: '07',
      totalFrom: 4,
      numberFrom: 2,
      totalTo: 3,
      numberTo: 4,
      note: '',
      order: 16,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_DT01',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
    {
      content: 'Tày',
      code: 'z',
      totalFrom: 1,
      numberFrom: 3,
      totalTo: 4,
      numberTo: 1,
      note: '',
      order: 17,
      level: 2,
      isSummary: false,
      idBieuNoiDung: 'f7e6c47d-78f9-4aa4-87de-b4fc3c06cc28',
      ma: 'B1-BIEU-1_T01_H004_DT02',
      maCha: 'B1-BIEU-1_T01_H004',
      style: 'font-size:14px;',
    },
  ],
};

const dataDefault: any[] = [
  {
    type: ETypeChart.Area,
    title: 'Line Chart One',
    series: [
      {
        field: 'totalFrom',
        name: 'Tổng số hộ tới',
        value: [
          [0, 0],
          [1, 1.3488096893269022],
          [2, 0.870353404927271],
          [4, 0.2582374710442245],
          [5, 3.4992630153517794],
          [6, 10.165796338844878],
          [7, 19.435802797730613],
          [8, 29.247221696220688],
          [9, 36.900573657650156],
          [10, 39.941591483707086],
          [11, 37.022903312892616],
          [12, 28.44151963796814],
          [13, 16.152947095922325],
          [14, 3.238238801433192],
          [19, 4.091031098382733],
          [20, 12.759421640647318],
        ],
      },
    ],
  },
  {
    title: 'Ring Chart',
    type: ETypeChart.RingHalfDonut,
    series: [
      {
        data: [{ value: 30, name: 'Tổng số hộ tới', field: 'totalFrom' }],
      },
    ],
    category: ['Quận Ba Đình'],
  },
  formatDataChart({ obj: table, type: ETypeChart.Bar, title: 'Bar Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.StackedBar, title: 'Stacked Bar Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Pie, title: 'Pie Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Ring, title: 'Ring Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Line, title: 'Line Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Scatter, title: 'Scatter Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Bubble, title: 'Bubble Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.Area, title: 'Area Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.StackedArea, title: 'Stacked Area Chart' }),
  formatDataChart({ obj: table, type: ETypeChart.LineBar, title: 'Line Bar Chart' }),
  {
    type: ETypeChart.Line,
    title: 'Line Chart One',
    series: [
      {
        field: 'totalFrom',
        name: 'Tổng số hộ tới',
        value: [
          [0, 0],
          [1, 1.3488096893269022],
          [2, 0.870353404927271],
          [4, 0.2582374710442245],
          [5, 3.4992630153517794],
          [6, 10.165796338844878],
          [7, 19.435802797730613],
          [8, 29.247221696220688],
          [9, 36.900573657650156],
          [10, 39.941591483707086],
          [11, 37.022903312892616],
          [12, 28.44151963796814],
          [13, 16.152947095922325],
          [14, 3.238238801433192],
          [19, 4.091031098382733],
          [20, 12.759421640647318],
        ],
      },
    ],
  },
];
const columns: IForm[] = [
  {
    name: 'Switch',
    title: 'Switch',
    formItem: {
      col: 4,
      type: EFormType.Switch,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'Radio',
    title: 'Radio',
    formItem: {
      col: 4,
      type: EFormType.Radio,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        { label: 'Value 2', value: '2' },
      ],
    },
  },
  {
    name: 'Checkbox',
    title: 'Checkbox',
    formItem: {
      col: 4,
      type: EFormType.Checkbox,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        { label: 'Value 2', value: '2' },
      ],
    },
  },
  {
    name: 'DateRange',
    title: 'DateRange',
    formItem: {
      col: 4,
      type: EFormType.DateRange,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'Time',
    title: 'Time',
    formItem: {
      col: 4,
      type: EFormType.Time,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'TimeRange',
    title: 'TimeRange',
    formItem: {
      col: 4,
      type: EFormType.TimeRange,
      rules: [{ type: EFormRuleType.Required }],
    },
  },
  {
    name: 'TreeSelect',
    title: 'TreeSelect',
    formItem: {
      col: 4,
      type: EFormType.TreeSelect,
      rules: [{ type: EFormRuleType.Required }],
      list: [
        { label: 'Value 1', value: '1' },
        {
          label: 'Value 2',
          value: '2',
          children: [
            { label: 'Value 1', value: '1' },
            { label: 'Value 2', value: '2' },
          ],
        },
      ],
    },
  },

  {
    title: 'Addable Table',
    name: 'Addable',
    formItem: {
      type: EFormType.Addable,
      rules: [{ type: EFormRuleType.Required }],
      addable: {
        textAdd: 'Add item',
        onAdd: value => console.log(value),
        isTable: true,
        showRemove: value => {
          console.log(value);
          return true;
        },
        idCheck: true,
      },
      column: [
        {
          title: 'hours',
          name: 'hours',
          formItem: {
            rules: [{ type: EFormRuleType.Required }],
            type: EFormType.Number,
          },
        },
      ],
    },
  },
  {
    title: 'Addable',
    name: 'Addable 2',
    formItem: {
      type: EFormType.Addable,
      rules: [{ type: EFormRuleType.Required }],
      addable: {
        textAdd: 'Add item',
        onAdd: value => console.log(value),
        isTable: false,
        showRemove: value => {
          console.log(value);
          return true;
        },
        idCheck: true,
      },
      column: [
        {
          title: 'hours',
          name: 'hours',
          formItem: {
            rules: [{ type: EFormRuleType.Required }],
            type: EFormType.Number,
          },
        },
      ],
    },
  },
];

// const initialTree = {
//   node1: {
//     id: 'node1',
//     children: ['node2', 'node3'],
//     attribute: {
//       type: 1,
//       status: 0,
//       cpu: '50 / 100',
//       ram: '200GB / 400GB',
//       speed: '1TB / 2TB',
//       online: '25',
//       offline: '5',
//       error: 30,
//     },
//   },
//   node2: {
//     id: 'node2',
//     attribute: {
//       type: 2,
//       status: 0,
//       cpu: '20 / 30',
//       ram: '80GB / 128GB',
//       speed: '400GB / 600GB',
//       online: '15',
//       offline: '5',
//       error: 20,
//     },
//   },
//   node3: {
//     id: 'node3',
//     children: ['node4', 'node5', 'node6'],
//     attribute: {
//       type: 2,
//       status: 0,
//       cpu: '20 / 30',
//       ram: '80GB / 128GB',
//       speed: '400GB / 600GB',
//       online: '15',
//       offline: '5',
//       error: 20,
//     },
//   },
//   node4: {
//     id: 'node4',
//     attribute: {
//       type: 3,
//       status: 0,
//     },
//   },
//   node5: {
//     id: 'node5',
//     children: ['node7', 'node8', 'node9'],
//     attribute: {
//       type: 3,
//       status: 1,
//     },
//   },
//   node6: {
//     id: 'node6',
//     attribute: {
//       type: 3,
//       status: -1,
//     },
//   },
//   node7: {
//     id: 'node7',
//     attribute: {
//       type: 4,
//       status: 0,
//     },
//   },
//   node8: {
//     id: 'node8',
//     attribute: {
//       type: 4,
//       status: 1,
//     },
//   },
//   node9: {
//     id: 'node9',
//     attribute: {
//       type: 4,
//       status: -1,
//     },
//   },
// };
// const task = [
//   {
//     id: '2',
//     name: 'Demolition',
//     assignee: '',
//     status: '',
//     priority: '',
//     planned: 43,
//     work: 42,
//     startDate: dayjs('2015-07-06'),
//     endDate: dayjs('2015-07-15'),
//     percent: 86,
//     children: [
//       {
//         id: '3',
//         name: 'Remove fixtures and cabinets',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-07-06'),
//         endDate: dayjs('2015-07-08'),
//         percent: 1,
//         success: '4',
//       },
//       {
//         id: '4',
//         name: 'Demolish interior walls',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-07-09'),
//         endDate: dayjs('2015-07-15'),
//         percent: 86,
//         success: '6',
//       },
//       {
//         id: '5',
//         name: 'Remove siding',
//         assignee: 'Jack Davolio',
//         status: 'Completed',
//         priority: 'Normal',
//         planned: 14,
//         work: 18,
//         startDate: dayjs('2015-07-06'),
//         endDate: dayjs('2015-07-07'),
//         percent: 50,
//         success: '6',
//       },
//       {
//         id: '6',
//         name: 'Demolition complete',
//         startDate: dayjs('2015-07-15'),
//       },
//     ],
//   },
//   {
//     id: '7',
//     name: 'Foundation',
//     assignee: 'Rose Fuller',
//     status: 'On Hold',
//     priority: 'Normal',
//     planned: 45,
//     work: 42,
//     startDate: dayjs('2015-07-06'),
//     endDate: dayjs('2015-08-07'),
//     percent: 72,
//     children: [
//       {
//         id: '8',
//         name: 'Excavate for foundation',
//         assignee: 'Fuller King',
//         status: 'Completed',
//         priority: 'Critical',
//         planned: 32,
//         work: 33,
//         startDate: dayjs('2015-07-06'),
//         endDate: dayjs('2015-07-14'),
//         percent: 100,
//         success: '9',
//       },
//       {
//         id: '9',
//         name: 'Build foundation',
//         assignee: 'Fuller King',
//         status: 'Completed',
//         priority: 'Critical',
//         planned: 32,
//         work: 33,
//         startDate: dayjs('2015-07-15'),
//         endDate: dayjs('2015-07-21'),
//         percent: 100,
//         success: '10',
//       },
//       {
//         id: '10',
//         name: 'Drying Time',
//         assignee: 'Fuller King',
//         status: 'Completed',
//         priority: 'Critical',
//         planned: 32,
//         work: 33,
//         startDate: dayjs('2015-07-22'),
//         endDate: dayjs('2015-08-04'),
//         percent: 100,
//         success: '11',
//       },
//       {
//         id: '11',
//         name: 'Complete foundation inspection',
//         assignee: 'Fuller King',
//         status: 'Completed',
//         priority: 'Critical',
//         planned: 32,
//         work: 33,
//         startDate: dayjs('2015-08-05'),
//         endDate: dayjs('2015-08-05'),
//         percent: 100,
//         success: '12',
//       },
//       {
//         id: '12',
//         name: 'Backfill foundation',
//         assignee: 'Fuller King',
//         status: 'Completed',
//         priority: 'Critical',
//         planned: 32,
//         work: 33,
//         startDate: dayjs('2015-08-06'),
//         endDate: dayjs('2015-08-07'),
//         percent: 100,
//         success: '13',
//       },
//       {
//         id: '13',
//         name: 'Basics complete',
//         startDate: dayjs('2015-08-07'),
//       },
//     ],
//   },
//   {
//     id: '14',
//     name: 'Framing, Walls, Door, and Windows',
//     assignee: '',
//     status: '',
//     priority: '',
//     planned: 43,
//     work: 42,
//     startDate: dayjs('2015-08-05'),
//     endDate: dayjs('2015-08-28'),
//     percent: 86,
//     children: [
//       {
//         id: '15',
//         name: 'Frame roof',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-10'),
//         endDate: dayjs('2015-08-14'),
//         percent: 1,
//         success: '16',
//       },
//       {
//         id: '16',
//         name: 'Close in roof',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-17'),
//         endDate: dayjs('2015-08-19'),
//         percent: 86,
//         success: '17,24',
//       },
//       {
//         id: '17',
//         name: 'Frame interior walls',
//         assignee: 'Jack Davolio',
//         status: 'Completed',
//         priority: 'Normal',
//         planned: 14,
//         work: 18,
//         startDate: dayjs('2015-08-20'),
//         endDate: dayjs('2015-08-26'),
//         percent: 50,
//         success: '18',
//       },
//       {
//         id: '18',
//         name: 'Framing complete',
//         startDate: dayjs('2015-08-26'),
//         success: '19,20,21',
//       },
//       {
//         id: '19',
//         name: 'Hang exterior doors',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-27'),
//         endDate: dayjs('2015-08-27'),
//         percent: 1,
//         success: '22',
//       },
//       {
//         id: '20',
//         name: 'Install windows',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-27'),
//         endDate: dayjs('2015-08-31'),
//         percent: 86,
//         success: '22',
//       },
//       {
//         id: '21',
//         name: 'Install siding',
//         assignee: 'Jack Davolio',
//         status: 'Completed',
//         priority: 'Normal',
//         planned: 14,
//         work: 18,
//         startDate: dayjs('2015-08-27'),
//         endDate: dayjs('2015-09-02'),
//         percent: 50,
//         success: '22',
//       },
//       {
//         id: '22',
//         name: 'Exterior complete',
//         startDate: dayjs('2015-09-02'),
//         success: '38',
//       },
//     ],
//   },

//   {
//     id: '23',
//     name: 'Interior work',
//     assignee: '',
//     status: '',
//     priority: '',
//     planned: 43,
//     work: 42,
//     startDate: dayjs('2015-08-19'),
//     endDate: dayjs('2015-09-04'),
//     percent: 86,
//     children: [
//       {
//         id: '24',
//         name: 'Interior finish work begins',
//         startDate: dayjs('2015-08-19'),
//         success: '38',
//       },
//       {
//         id: '25',
//         name: 'Utilities',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-20'),
//         endDate: dayjs('2015-08-27'),
//         percent: 1,
//         children: [
//           {
//             id: '26',
//             name: 'Rough-in plumbing',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-08-20'),
//             endDate: dayjs('2015-08-27'),
//             percent: 86,
//             success: '30',
//           },
//           {
//             id: '27',
//             name: 'Rough-in electrical',
//             assignee: 'Jack Davolio',
//             status: 'Completed',
//             priority: 'Normal',
//             planned: 14,
//             work: 18,
//             startDate: dayjs('2015-08-20'),
//             endDate: dayjs('2015-08-26'),
//             percent: 50,
//             success: '30',
//           },
//           {
//             id: '28',
//             name: 'Rough-in HVAC',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-08-20'),
//             endDate: dayjs('2015-08-25'),
//             percent: 1,
//             success: '30',
//           },
//           {
//             id: '29',
//             name: 'Rough-in communication cabling',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-08-20'),
//             endDate: dayjs('2015-08-21'),
//             percent: 86,
//             success: '30',
//           },
//         ],
//       },
//       {
//         id: '30',
//         name: 'Utilities rough-in complete',
//         startDate: dayjs('2015-08-27'),
//         success: '35',
//       },
//       {
//         id: '31',
//         name: 'Finish interior walls',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-20'),
//         endDate: dayjs('2015-08-25'),
//         percent: 1,
//         children: [
//           {
//             id: '32',
//             name: 'Install drywall',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-08-20'),
//             endDate: dayjs('2015-08-24'),
//             percent: 86,
//             success: '33',
//           },
//           {
//             id: '33',
//             name: 'Paint interior',
//             assignee: 'Jack Davolio',
//             status: 'Completed',
//             priority: 'Normal',
//             planned: 14,
//             work: 18,
//             startDate: dayjs('2015-08-23'),
//             endDate: dayjs('2015-08-25'),
//             percent: 50,
//             success: '35',
//           },
//         ],
//       },
//       {
//         id: '34',
//         name: 'Finish Utilities',
//         assignee: 'Martin Tamer',
//         status: 'Completed',
//         priority: 'High',
//         planned: 43,
//         work: 42,
//         startDate: dayjs('2015-08-27'),
//         endDate: dayjs('2015-09-04'),
//         percent: 1,
//         children: [
//           {
//             id: '35',
//             name: 'Finish utilities begin',
//             startDate: dayjs('2015-08-27'),
//             success: '36,37,38,39',
//           },
//           {
//             id: '36',
//             name: 'Complete plumbing',
//             assignee: 'Jack Davolio',
//             status: 'Completed',
//             priority: 'Normal',
//             planned: 14,
//             work: 18,
//             startDate: dayjs('2015-08-28'),
//             endDate: dayjs('2015-09-01'),
//             percent: 50,
//             success: '40',
//           },
//           {
//             id: '37',
//             name: 'Complete electrical wiring',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-08-28'),
//             endDate: dayjs('2015-09-03'),
//             percent: 1,
//             success: '40',
//           },
//           {
//             id: '38',
//             name: 'Complete communication cabling',
//             assignee: 'Martin Tamer',
//             status: 'Completed',
//             priority: 'High',
//             planned: 43,
//             work: 42,
//             startDate: dayjs('2015-09-03'),
//             endDate: dayjs('2015-09-04'),
//             percent: 86,
//             success: '40',
//           },
//           {
//             id: '39',
//             name: 'Complete HVAC',
//             assignee: 'Jack Davolio',
//             status: 'Completed',
//             priority: 'Normal',
//             planned: 14,
//             work: 18,
//             startDate: dayjs('2015-08-28'),
//             endDate: dayjs('2015-08-28'),
//             percent: 50,
//             success: '40',
//           },
//           {
//             id: '40',
//             name: 'Complete Project',
//             startDate: dayjs('2015-09-04'),
//           },
//         ],
//       },
//     ],
//   },
// ];
// const event = [
//   {
//     name: 'New Year holiday',
//     startDate: dayjs('2015-07-15'),
//     endDate: dayjs('2015-07-16'),
//   },
//   {
//     name: 'Christmas holidays',
//     startDate: dayjs('2015-08-15'),
//     endDate: dayjs('2015-08-15'),
//   },
//   {
//     name: 'Q-1 Release',
//     startDate: dayjs('2015-07-09'),
//   },
//   // {
//   //   name: 'Q-2 Release',
//   //   startDate: dayjs('2015-07-30'),
//   // },
//   // {
//   //   name: 'Q-3 Release',
//   //   startDate: dayjs('2015-08-10'),
//   // },
// ];
